# Generated by Django 3.0.6 on 2020-06-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='Resumo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livros',
            name='Valor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livros',
            name='Image',
            field=models.ImageField(upload_to='capas'),
        ),
    ]
